default_language_version:
    python: python3.12

exclude: ^(.semgrep|vendored)/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^templates/templated_email/compiled/
        exclude_types: [svg,graphql]
      - id: end-of-file-fixer
        exclude: ^templates/templated_email/compiled/
        exclude_types: [svg]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: uv run mypy
        args: [--cache-dir=/dev/null]
        types: [python]
        exclude: (tests|vendored)/

  - repo: local
    hooks:
      - id: deptry
        name: deptry
        language: system
        entry: uv run deptry
        args: [.]
        pass_filenames: false

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.14
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: Check for uncreated migrations.
        entry: sh -c "uv run ./manage.py makemigrations --check --dry-run"
        files: "models\\.py$"
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: gql-schema-check
        language: system
        name: Check GraphQL schema is up to date.
        entry: sh -c "./manage.py get_graphql_schema | diff saleor/graphql/schema.graphql -"
        stages: [pre-commit]
